# Theoretical Questions:

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Answer:

NumPy provides support for arrays and matrices, along with a large collection of mathematical functions to operate on these arrays. It enhances Python by providing high-performance multidimensional array objects and tools to work with these arrays efficiently, making it faster than using Pythons built-in lists for numerical computations.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Answer: 

np.mean() computes the arithmetic mean of an array, while np.average() computes the weighted average. You would use np.average() if you need to assign different weights to the data points, and np.mean() when no weights are needed.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Answer: 

To reverse a 1D array, you can use slicing [: :-1]. For a 2D array, np.flip() can reverse the array along the specified axis, such as np.flip(arr, axis=0) for rows or np.flip(arr, axis=1) for columns.

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Answer: 

The data type of a NumPy array can be determined using arr.dtype. Data types are important in NumPy as they affect memory consumption and performance, allowing for optimizations when handling large datasets.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Answer: 

ndarray is the core object in NumPy and represents a n-dimensional array. It differs from Python lists by being homogeneous (all elements have the same type), supporting vectorized operations, and consuming less memory due to its contiguous storage.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Answer: 

NumPy arrays provide significant performance benefits due to their ability to perform operations in a vectorized manner, without the need for explicit loops. This results in faster computations and lower memory usage compared to Python lists.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Answer: 

vstack() vertically stacks arrays (along the rows), while hstack() horizontally stacks arrays (along the columns). They are useful for concatenating arrays.

In [4]:
# example
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack arrays vertically and horizontally
stacked_array_vertical = np.vstack([arr1, arr2])
stacked_array_horizontal = np.hstack([arr1, arr2])

print("Vertically stacked array:")
print(stacked_array_vertical)

print("\nHorizontally stacked array:")
print(stacked_array_horizontal)

Vertically stacked array:
[[1 2 3]
 [4 5 6]]

Horizontally stacked array:
[1 2 3 4 5 6]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Answer: 

fliplr() flips an array left to right (horizontally), while flipud() flips an array upside down (vertically). These functions are helpful when you need to reverse arrays along specific axes.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Answer: 

array_split() splits an array into multiple sub-arrays. If the array cannot be split evenly, the last sub-array will have fewer elements than the others.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Answer: 

Vectorization allows for performing operations on entire arrays without explicit loops, making the code faster. Broadcasting automatically expands arrays with differing shapes to make them compatible for element-wise operations, eliminating the need for manual reshaping.

# Practical Questions:

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [5]:
arr = np.random.randint(1, 100, (3, 3))
arr.T  # Transposes the array, interchanging rows and columns


array([[27, 39, 43],
       [97, 13, 35],
       [25, 50, 32]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [9]:
arr = np.arange(10)
arr1 = arr.reshape(2, 5)
arr2 = arr.reshape(5, 2)
print("Array 1: \n")
print(arr1)
print("\n\nArray 2: \n")
print(arr2)

Array 1: 

[[0 1 2 3 4]
 [5 6 7 8 9]]


Array 2: 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [11]:
arr = np.random.rand(4, 4)
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
bordered_arr


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.20526722e-02, 4.73664247e-01, 9.65819792e-01,
        8.71088453e-01, 0.00000000e+00],
       [0.00000000e+00, 6.81109695e-01, 7.95928834e-01, 4.12019112e-01,
        6.34607086e-01, 0.00000000e+00],
       [0.00000000e+00, 4.71702993e-01, 2.75590633e-01, 1.34501804e-01,
        3.75751784e-04, 0.00000000e+00],
       [0.00000000e+00, 1.99014255e-01, 2.49633359e-01, 7.89231731e-01,
        4.97946024e-01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [13]:
arr = np.arange(10, 61, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [15]:
arr = np.array(['python', 'numpy', 'pandas'])
upper = np.char.upper(arr)
lower = np.char.lower(arr)
title = np.char.title(arr)
print(upper)
print(lower)
print(title)

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [17]:
arr = np.array(['python', 'numpy', 'pandas'])
spaced = np.char.join(' ', arr)
spaced

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [21]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2
print("addition: \n")
print(addition)
print("\nsubtraction\n")
print(subtraction)
print("\nmultiplication\n")
print(multiplication)
print("\ndivision\n")
print(division)

addition: 

[[ 6  8]
 [10 12]]

subtraction

[[-4 -4]
 [-4 -4]]

multiplication

[[ 5 12]
 [21 32]]

division

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.



In [24]:
identity_matrix = np.eye(5)
diagonal = np.diag(identity_matrix)
diagonal

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [26]:
arr = np.random.randint(0, 1000, 100)
primes = arr[np.array([np.all(arr[i] % np.arange(2, arr[i])) for i in range(len(arr))])]
primes

array([739, 113, 797, 223, 211, 941, 467, 523, 907, 223, 487, 211, 251,
       419, 197, 929,   5, 673])

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.



In [29]:
daily_temps = np.random.randint(15, 35, 28) 

weekly_chunks = daily_temps.reshape(-1, 7)
weekly_avg = np.mean(weekly_chunks, axis=1)

print(weekly_avg)

[27.         24.71428571 25.42857143 27.28571429]
